package world.gregs.hestia.game.map

object Flags {

    const val FLOOR_BLOCKS_WALK = 0x200000
    const val FLOOR_DECO_BLOCKS_WALK = 0x40000

    const val OBJ = 0x100
    const val OBJ_BLOCKS_FLY = 0x20000
    const val OBJ_BLOCKS_WALK_ALTERNATIVE = 0x40000000

    const val WALL_OBJ_NORTH = 0x2
    const val WALL_OBJ_EAST = 0x8
    const val WALL_OBJ_SOUTH = 0x20
    const val WALL_OBJ_WEST = 0x80

    const val CORNER_OBJ_NORTH_WEST = 0x1
    const val CORNER_OBJ_NORTH_EAST = 0x4
    const val CORNER_OBJ_SOUTH_EAST = 0x10
    const val CORNER_OBJ_SOUTH_WEST = 0x40

    const val WALL_OBJ_NORTH_BLOCKS_FLY = 0x400
    const val WALL_OBJ_EAST_BLOCKS_FLY = 0x1000
    const val WALL_OBJ_SOUTH_BLOCKS_FLY = 0x4000
    const val WALL_OBJ_WEST_BLOCKS_FLY = 0x10000

    const val CORNER_OBJ_NORTH_WEST_BLOCKS_FLY = 0x200
    const val CORNER_OBJ_NORTH_EAST_BLOCKS_FLY = 0x800
    const val CORNER_OBJ_SOUTH_EAST_BLOCKS_FLY = 0x2000
    const val CORNER_OBJ_SOUTH_WEST_BLOCKS_FLY = 0x8000

    const val WALL_OBJ_NORTH_BLOCKS_WALK_ALTERNATIVE = 0x800000
    const val WALL_OBJ_EAST_BLOCKS_WALK_ALTERNATIVE = 0x2000000
    const val WALL_OBJ_SOUTH_BLOCKS_WALK_ALTERNATIVE = 0x8000000
    const val WALL_OBJ_WEST_BLOCKS_WALK_ALTERNATIVE = 0x20000000

    const val CORNER_OBJ_NORTH_WEST_BLOCKS_WALK_ALTERNATIVE = 0x400000
    const val CORNER_OBJ_NORTH_EAST_BLOCKS_WALK_ALTERNATIVE = 0x1000000
    const val CORNER_OBJ_SOUTH_EAST_BLOCKS_WALK_ALTERNATIVE = 0x4000000
    const val CORNER_OBJ_SOUTH_WEST_BLOCKS_WALK_ALTERNATIVE = 0x10000000

    val FLAG_GROUPS = arrayOf(
            arrayOf(
                    intArrayOf(WALL_OBJ_NORTH, WALL_OBJ_EAST, WALL_OBJ_SOUTH, WALL_OBJ_WEST),
                    intArrayOf(CORNER_OBJ_NORTH_WEST, CORNER_OBJ_NORTH_EAST, CORNER_OBJ_SOUTH_EAST, CORNER_OBJ_SOUTH_WEST)
            ),
            arrayOf(
                    intArrayOf(WALL_OBJ_NORTH_BLOCKS_FLY, WALL_OBJ_EAST_BLOCKS_FLY, WALL_OBJ_SOUTH_BLOCKS_FLY, WALL_OBJ_WEST_BLOCKS_FLY),
                    intArrayOf(CORNER_OBJ_NORTH_WEST_BLOCKS_FLY, CORNER_OBJ_NORTH_EAST_BLOCKS_FLY, CORNER_OBJ_SOUTH_EAST_BLOCKS_FLY, CORNER_OBJ_SOUTH_WEST_BLOCKS_FLY)
            ),
            arrayOf(
                    intArrayOf(WALL_OBJ_NORTH_BLOCKS_WALK_ALTERNATIVE, WALL_OBJ_EAST_BLOCKS_WALK_ALTERNATIVE, WALL_OBJ_SOUTH_BLOCKS_WALK_ALTERNATIVE, WALL_OBJ_WEST_BLOCKS_WALK_ALTERNATIVE),
                    intArrayOf(CORNER_OBJ_NORTH_WEST_BLOCKS_WALK_ALTERNATIVE, CORNER_OBJ_NORTH_EAST_BLOCKS_WALK_ALTERNATIVE, CORNER_OBJ_SOUTH_EAST_BLOCKS_WALK_ALTERNATIVE, CORNER_OBJ_SOUTH_WEST_BLOCKS_WALK_ALTERNATIVE)
            )
    )

    val EXTRA_FLAGS = arrayOf(
            intArrayOf(130, 10, 40, 160),
            intArrayOf(0x10400, 5120, 20480, 0x14000),
            intArrayOf(0x20800000, 0x2800000, 0xa000000, 0x28000000)
    )
}