package worlds.gregs.hestia.network.client

import world.gregs.hestia.core.network.codec.MessageHandshakeCodec
import world.gregs.hestia.core.network.protocol.decoders.LoginHandshakeDecoder
import world.gregs.hestia.core.network.protocol.decoders.PingDecoder
import world.gregs.hestia.core.network.protocol.encoders.*
import worlds.gregs.hestia.network.client.decoders.*
import worlds.gregs.hestia.network.client.encoders.*

class ClientCodec : MessageHandshakeCodec() {

    init {
        bind(GameLoginDecoder(), true)
        bind(LoginHandshakeDecoder(), true)

        bind(ConsoleCommandDecoder())
        bind(CutsceneActionDecoder())
        bind(DialogueContinueDecoder())
        bind(IntegerEntryDecoder())
        bind(SecondaryTeleportDecoder())
        bind(FloorItemOptionDecoder())
        bind(KeysPressedDecoder())
        bind(LatencyDecoder())
        bind(NpcOptionDecoder())
        bind(MovedCameraDecoder())
        bind(MovedMouseDecoder())
        bind(ObjectOptionDecoder())
        bind(PlayerOptionDecoder())
        bind(ReceiveCountDecoder())
        bind(ReflectionResponseDecoder())
        bind(RegionLoadedDecoder())
        bind(RegionLoadingDecoder())
        bind(ScreenChangeDecoder())
        bind(ScreenCloseDecoder())
        bind(ClanNameDecoder())
        bind(ResumeObjDialogueDecoder())
        bind(ClanForumThreadDecoder())
        bind(ClanChatKickDecoder())
        bind(UnknownScriptDecoder())
        bind(SkillcapeColourDecoder())
        bind(StringEntryDecoder())
        bind(ToolkitPreferencesDecoder())
        bind(PingReplyDecoder())
        bind(APCoordinateDecoder())
        bind(ClanSettingsUpdateDecoder())
        bind(UnknownDecoder())
        bind(WalkMapDecoder())
        bind(WalkMiniMapDecoder())
        bind(InterfaceOnFloorItemDecoder())
        bind(InterfaceOnNpcDecoder())
        bind(InterfaceOnObjectDecoder())
        bind(InterfaceOnPlayerDecoder())
        bind(InterfaceOnInterfaceDecoder())
        bind(InterfaceOptionDecoder())
        bind(InterfaceSwitchComponentsDecoder())
        bind(WindowClickDecoder())
        bind(WindowFocusDecoder())
        bind(WindowHoveredDecoder())
        bind(WorldMapOpenDecoder())
        bind(PingDecoder())

        bind(ClientResponseEncoder())
        bind(InterfaceSettingsEncoder())
        bind(InterfaceVisibilityEncoder())
        bind(InterfaceSpriteEncoder())
        bind(VarpEncoder())
        bind(VarbitEncoder())
        bind(VarcEncoder())
        bind(VarcStrEncoder())
        bind(FloorItemClearEncoder())
        bind(FloorItemPrivateEncoder())
        bind(FloorItemPublicEncoder())
        bind(FloorItemRemoveEncoder())
        bind(FloorItemUpdateEncoder())
        bind(FriendListDisconnectEncoder())
        bind(LoginDetailsEncoder())
        bind(LogoutEncoder())
        bind(MapRegionDynamicEncoder())
        bind(MapRegionEncoder())
        bind(RunEnergyEncoder())
        bind(ScriptEncoder())
        bind(SkillLevelEncoder())
        bind(InterfaceCloseEncoder())
        bind(InterfaceAnimationEncoder())
        bind(InterfaceComponentTextEncoder())
        bind(InterfaceHeadNpcEncoder())
        bind(InterfaceHeadPlayerEncoder())
        bind(InterfaceItemEncoder())
        bind(InterfaceItemsEncoder())
        bind(InterfaceOpenEncoder())
        bind(WindowUpdateEncoder())
        bind(PlayerContextMenuOptionEncoder())
        bind(PlayerUpdateEncoder())
        bind(NpcUpdateEncoder())
        bind(ClientMessageOutEncoder())
        bind(ChunkEncoder())

        bind(ChatEncoder())
        bind(FriendsChatDisconnectEncoder())
        bind(FriendListUnlockEncoder())
    }
}